version: '3.8'

services:
  redis:
    image: redis:7.0.4-alpine
    restart: always
    ports:
      - 6379:6379
  database:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=socrates
    ports:
      - 5432:5432
